#!/bin/bash
# doc-detect.sh — shared helper: detect project-doc documentation (.claude/CLAUDE.md + .claude/docs/).
#
# Two modes:
#   doc-detect.sh <dir>          → descend up to 3 levels, list every project with a doc
#   doc-detect.sh --one <proj>   → report only <proj> (used by the guard)
#
# Emits TSV lines: DOC<TAB>project_dir<TAB>n_docs<TAB>n_changed_since_gen
# (4th column = staleness: files changed in git since the doc was generated; 0 if
# fresh / not a git repo / no generation date.)
# Fail-open: any error → no output, exit 0. Never blocks the caller.

# doc_staleness <project_dir> — count tracked files changed (excluding .claude/)
# since the doc's "Generated by /project-doc on YYYY-MM-DD" date. Best-effort.
doc_staleness() {
  local PROJ="$1" GEN_DATE CHANGED
  [ -d "$PROJ/.git" ] || { echo 0; return; }
  GEN_DATE=$(grep -oE 'Generated by /project-doc on [0-9]{4}-[0-9]{2}-[0-9]{2}' "$PROJ/.claude/CLAUDE.md" 2>/dev/null \
    | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' | head -1)
  [ -z "$GEN_DATE" ] && { echo 0; return; }
  CHANGED=$(git -C "$PROJ" log --since="$GEN_DATE 00:00:00" --name-only --pretty=format: 2>/dev/null \
    | grep -v '^$' | grep -v '^\.claude/' | sort -u | wc -l | tr -d ' ')
  echo "${CHANGED:-0}"
}

# doc_line <project_dir> — print one TSV line if project_dir has a project-doc CLAUDE.md.
doc_line() {
  local PROJ="$1"
  [ -f "$PROJ/.claude/CLAUDE.md" ] || return 1
  local N STALE
  N=$(find "$PROJ/.claude/docs" -type f -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  STALE=$(doc_staleness "$PROJ")
  printf 'DOC\t%s\t%s\t%s\n' "$PROJ" "${N:-0}" "${STALE:-0}"
}

# --one mode: just report the given project dir.
if [ "$1" = "--one" ]; then
  doc_line "$2"
  exit 0
fi

# descend mode: scan <dir> + up to a few levels for .claude/CLAUDE.md.
ROOT="${1:-$PWD}"
[ -d "$ROOT" ] || exit 0

DOC_FILES=$(find "$ROOT" -maxdepth 6 -type d \( -name node_modules -o -name .git \) -prune \
  -o -type f -path '*/.claude/CLAUDE.md' -print 2>/dev/null)
[ -z "$DOC_FILES" ] && exit 0

while IFS= read -r CMD; do
  [ -z "$CMD" ] && continue
  PROJ=$(dirname "$(dirname "$CMD")")   # project dir = parent of .claude
  doc_line "$PROJ"
done <<< "$DOC_FILES"
exit 0
