#!/bin/bash
# doc-detect.sh — shared helper: detect project-doc documentation (CLAUDE.md + .claude/docs/).
#
# CLAUDE.md location: Claude Code's native convention is project ROOT (confirmed
# empirically — that's where the harness actually loads project instructions from);
# some older project-doc runs wrote it nested at .claude/CLAUDE.md. Both are accepted
# (root checked first) — see find_claude_md(). Fixing a real bug: the detection used
# to hardcode .claude/CLAUDE.md only, so it silently found nothing for root-CLAUDE.md
# projects (e.g. Cybersec) and could escalate up to an unrelated ancestor directory.
#
# Two modes:
#   doc-detect.sh <dir>          → descend up to 3 levels, list every project with a doc
#   doc-detect.sh --one <proj>   → report only <proj> (used by the guard)
#
# Emits TSV lines: DOC<TAB>project_dir<TAB>n_docs<TAB>n_changed_since_gen<TAB>out_of_pattern
# (4th column = staleness: files changed in git since the doc was generated; 0 if
# fresh / not a git repo / no generation date.)
# (5th column = out_of_pattern: 1 if pattern_check reports in_pattern=false; 0 otherwise.
# Fails open: python missing / lib missing / any error → 0, never blocks the caller.)
# Fail-open: any error → no output, exit 0. Never blocks the caller.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATTERN_CHECK_PY="$SCRIPT_DIR/../lib/pattern_check.py"

# find_claude_md <project_dir> — prints the CLAUDE.md path. Prefers whichever
# location actually carries the project-doc:v2 marker (handles projects that have
# BOTH — e.g. a hand-written root CLAUDE.md alongside the real, project-doc-
# generated nested one, seen in the wild: MED-COMPANION). Falls back to
# root-then-nested existence when neither/the check is inconclusive. Prints
# nothing if neither exists.
find_claude_md() {
  local PROJ="$1"
  local ROOT_MD="$PROJ/CLAUDE.md" NESTED_MD="$PROJ/.claude/CLAUDE.md"
  if [ -f "$ROOT_MD" ] && grep -q 'project-doc:v2' "$ROOT_MD" 2>/dev/null; then
    printf '%s' "$ROOT_MD"; return
  fi
  if [ -f "$NESTED_MD" ] && grep -q 'project-doc:v2' "$NESTED_MD" 2>/dev/null; then
    printf '%s' "$NESTED_MD"; return
  fi
  if [ -f "$ROOT_MD" ]; then
    printf '%s' "$ROOT_MD"
  elif [ -f "$NESTED_MD" ]; then
    printf '%s' "$NESTED_MD"
  fi
}

# doc_out_of_pattern <project_dir> — returns 1 if in_pattern=false, 0 otherwise.
# Fails open: python missing / lib missing / any error → 0.
doc_out_of_pattern() {
  local PROJ="$1"
  [ -f "$PATTERN_CHECK_PY" ] || { echo 0; return; }
  local PY3
  PY3=$(command -v python3 2>/dev/null)
  [ -z "$PY3" ] && { echo 0; return; }
  local JSON IN_PAT
  JSON=$("$PY3" "$PATTERN_CHECK_PY" --project-root "$PROJ" --json 2>/dev/null)
  # Note: pattern_check.py exits 1 when out_of_pattern — that is not an error here;
  # bail only if JSON is empty (crash / missing lib / permission error).
  [ -z "$JSON" ] && { echo 0; return; }
  IN_PAT=$(printf '%s' "$JSON" | grep -o '"in_pattern": *[^,}]*' | grep -o 'true\|false' | head -1)
  if [ "$IN_PAT" = "false" ]; then echo 1; else echo 0; fi
}

# doc_staleness <project_dir> — count tracked files changed (excluding .claude/)
# since the doc's "Generated by /project-doc on YYYY-MM-DD" date. Best-effort.
doc_staleness() {
  local PROJ="$1" CLAUDE_MD GEN_DATE CHANGED
  [ -d "$PROJ/.git" ] || { echo 0; return; }
  CLAUDE_MD=$(find_claude_md "$PROJ")
  [ -z "$CLAUDE_MD" ] && { echo 0; return; }
  GEN_DATE=$(grep -oE 'Generated by /project-doc on [0-9]{4}-[0-9]{2}-[0-9]{2}' "$CLAUDE_MD" 2>/dev/null \
    | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' | head -1)
  [ -z "$GEN_DATE" ] && { echo 0; return; }
  CHANGED=$(git -C "$PROJ" log --since="$GEN_DATE 00:00:00" --name-only --pretty=format: 2>/dev/null \
    | grep -v '^$' | grep -v '^\.claude/' | sort -u | wc -l | tr -d ' ')
  echo "${CHANGED:-0}"
}

# doc_line <project_dir> — print one TSV line if project_dir has a project-doc CLAUDE.md
# (root or nested) AND a .claude/docs/ dir — the dir requirement keeps an arbitrary
# hand-written root CLAUDE.md (no project-doc docs) from being reported as a project-doc
# project now that root is checked too.
doc_line() {
  local PROJ="$1" CLAUDE_MD
  CLAUDE_MD=$(find_claude_md "$PROJ")
  [ -z "$CLAUDE_MD" ] && return 1
  [ -d "$PROJ/.claude/docs" ] || return 1
  local N STALE OOP
  N=$(find "$PROJ/.claude/docs" -type f -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  STALE=$(doc_staleness "$PROJ")
  OOP=$(doc_out_of_pattern "$PROJ")
  printf 'DOC\t%s\t%s\t%s\t%s\n' "$PROJ" "${N:-0}" "${STALE:-0}" "${OOP:-0}"
}

# --one mode: just report the given project dir.
if [ "$1" = "--one" ]; then
  doc_line "$2"
  exit 0
fi

# descend mode: scan <dir> + up to a few levels for CLAUDE.md (root or nested).
ROOT="${1:-$PWD}"
[ -d "$ROOT" ] || exit 0

DOC_FILES=$(find "$ROOT" -maxdepth 6 -type d \( -name node_modules -o -name .git \) -prune \
  -o -type f -name 'CLAUDE.md' -print 2>/dev/null)
[ -z "$DOC_FILES" ] && exit 0

SEEN=""
while IFS= read -r CMD; do
  [ -z "$CMD" ] && continue
  case "$CMD" in
    */.claude/CLAUDE.md) PROJ=$(dirname "$(dirname "$CMD")") ;;   # project dir = parent of .claude
    *)                   PROJ=$(dirname "$CMD") ;;                # root CLAUDE.md
  esac
  case "$SEEN" in *"|${PROJ}|"*) continue ;; esac   # dedupe (a project can have both)
  SEEN="${SEEN}|${PROJ}|"
  doc_line "$PROJ"
done <<< "$DOC_FILES"
exit 0
